[package]
name = "evobf"
version = "0.1.0"
authors = ["Aaron Kofsky <a2aarontothe2@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
pixel-canvas = "0.2.1"


[profile.dev.package."*"]
opt-level = 3
