[package]
name = "evobf"
version = "0.1.0"
authors = ["Aaron Kofsky <a2aarontothe2@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
pixel-canvas = "0.2.1"
rayon = "1.3.1"


[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
